import {StyleSheet} from 'react-native';
import {Colors} from 'utils/colors';
import Fonts from "../../utils/fonts"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header_place: {
    display: 'flex',
    flexDirection: 'row',
  },
  header_text: {
    fontWeight: 'bold',
    fontSize: 17,
    marginRight: '43%',
    marginTop: 4.5,
    color: Colors.black,
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    fontWeight: 'bold',
    color:Colors.light
  },
  itemtext: {color: Colors.light, fontWeight: 'bold'},
  textr: {color: Colors.light, fontWeight: 'bold'},
  addtoPortfolio: {
    backgroundColor: Colors.black,
    marginTop: 30,
    borderWidth: 0,
    zIndex: -1,
  },
  choose_network: {
    fontSize: 20,
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 25,
    fontFamily: Fonts.Bold,
    color: Colors.black,
  },
  chain_note: {
    textAlign: 'center',
    color: Colors.lighter,
    width: '80%',
    alignSelf: 'center',
    fontSize: 12,
    marginTop: 30,
    marginBottom: 10,
  },
  manual_note: {
    textAlign: 'center',
    color: Colors.lighter,
    width: '80%',
    alignSelf: 'center',
    fontSize: 13,
    marginTop: 0,
    marginBottom: 10,
    lineHeight: 18,
  },
  title: {
    fontSize: 15,
    fontFamily: Fonts.Bold,
    color: '#fff',
    marginLeft: 15,
    marginBottom: 5,
    marginTop: 0,
  },
  logoimg: {
    width: 25,
    height: 25,
    marginRight: 15,
    justifyContent: 'center',
    alignSelf: 'center',
    opacity: 0.9,
    marginVertical: 5,
  },
  viewStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 15,
    paddingVertical: 3,
  },
  coingecko: {
    marginLeft: 20,
    marginBottom: 50,
    marginTop: 10,
    fontSize: 11,
    color: 'gray',
  },
  viewStatsDetail: {
    paddingHorizontal: 20,
    borderRadius: 15,
    margin: 10,
    marginTop: -15,
    padding: 20,
    backgroundColor:Colors.btnback,
    borderWidth: 5,
    borderColor: Colors.btnback,
  },
  txtBg: {
    color: 'gray',
    textAlign: 'center',
    fontSize: 30,
    position: 'absolute',
    fontWeight: 'bold',
    zIndex: -1,
    opacity: 0.2,
    width: '100%',
  },
  subcont: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 0,
  },
  linechart: {
    justifyContent: 'center',
    height: 160,
    marginTop: 0,
    paddingHorizontal: 0,
  },
  chart: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingTop: 10,
  },
  title2: {
    fontSize: 14,
    fontFamily: Fonts.Bold,
    color: 'white',
    marginTop: 0,
    justifyContent: 'center',
    alignContent: 'flex-end',
    alignSelf: 'flex-end',
    paddingHorizontal: 5,
  },
  change: {
    color: Colors.inverse,
    textAlign: 'center',
    padding: 3,
    marginTop: 3,
    fontFamily: Fonts.Bold,
    borderRadius: 5,
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'flex-end',
  },
  subTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: Fonts.Bold,
    color: Colors.light,
    marginLeft: 20,
  },
  subTitleTop: {
    fontSize: 15,
    fontFamily: Fonts.regular,
    color: '#fff',
    marginLeft: 15,
  },
  smallContainer: {
    flexDirection: 'row',
    marginHorizontal: 0,
    marginVertical: 10,
    justifyContent: 'space-around',
    padding: 20,
    backgroundColor: Colors.black,
  },
  smallTitle: {
    fontSize: 16,
    fontFamily: Fonts.Bold,
    marginBottom: 5,
    color: Colors.black,
  },
  moreBtn: {
    paddingHorizontal: 5,
    justifyContent: 'space-around',
    paddingRight: 15,
  },
});
